using System;
using System.Collections.Generic;

namespace WorkflowAutomation.Domain.Entities.BetterAuth
{
    /// <summary>
    /// Entity representing the Better Auth 'auth_users' table.
    /// This table stores user identity information managed by Better Auth.
    /// The 'role' column stores a comma-separated list of role names.
    /// </summary>
    public class AuthUser
    {
        /// <summary>
        /// Primary key - UUID string generated by Better Auth.
        /// </summary>
        public string Id { get; set; } = string.Empty;

        /// <summary>
        /// User's display name (typically "FirstName LastName").
        /// </summary>
        public string? Name { get; set; }

        /// <summary>
        /// User's email address (unique).
        /// </summary>
        public string Email { get; set; } = string.Empty;

        /// <summary>
        /// Whether the email has been verified.
        /// </summary>
        public bool EmailVerified { get; set; }

        /// <summary>
        /// URL to user's profile image (optional).
        /// </summary>
        public string? Image { get; set; }

        /// <summary>
        /// Timestamp when the user was created.
        /// </summary>
        public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

        /// <summary>
        /// Timestamp when the user was last updated.
        /// </summary>
        public DateTime UpdatedAt { get; set; } = DateTime.UtcNow;

        /// <summary>
        /// Comma-separated list of role names (e.g., "admin,approver").
        /// This is the source of truth for authorization in the app.
        /// </summary>
        public string? Role { get; set; }

        /// <summary>
        /// Whether the user is banned/disabled.
        /// </summary>
        public bool Banned { get; set; }

        /// <summary>
        /// Reason for the ban (optional).
        /// </summary>
        public string? BanReason { get; set; }

        /// <summary>
        /// When the ban expires (null = permanent if banned).
        /// </summary>
        public DateTime? BanExpires { get; set; }

        // Navigation properties
        public virtual ICollection<AuthSession> Sessions { get; set; } = new List<AuthSession>();
        public virtual ICollection<AuthAccount> Accounts { get; set; } = new List<AuthAccount>();
    }
}
